/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.guiproject;

import java.io.FileWriter;
import java.io.Writer;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CashierRegisterInterface extends javax.swing.JFrame {

    /**
     * Creates new form CashierRegisterInterface
     */
    public CashierRegisterInterface() {
        initComponents();
        //set Tital 
        this.setTitle("Cashier Registration");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        padtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        cashierId = new javax.swing.JTextField();
        cashierUsername = new javax.swing.JTextField();
        register1 = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(padtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 224, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cashier Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        id.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("Enter Cashier ID :");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        username.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Cashier Username :");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        password.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password :");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        cashierId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierIdActionPerformed(evt);
            }
        });
        getContentPane().add(cashierId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 226, -1));

        cashierUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(cashierUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 224, -1));

        register1.setText("Register ");
        register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register1ActionPerformed(evt);
            }
        });
        getContentPane().add(register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashierUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashierUsernameActionPerformed

    private void register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register1ActionPerformed
        String id = cashierId.getText().trim();
        String name = cashierUsername.getText().trim();
        String password = padtxt.getText().trim();

        // Check if any of the fields are empty
        if (id.isEmpty() || name.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return; // Early return if fields are empty
        }

        try {
            // Use FileWriter to append to the file, and add a newline after each entry
            FileWriter writer = new FileWriter("Cashierregistration.txt", true);
            writer.write(id + "," + name + "," + password + "\n"); // Add newline character
            writer.close();
            JOptionPane.showMessageDialog(this, "User registration successful!");

            // Clear text fields
            cashierId.setText("");
            cashierUsername.setText("");
            padtxt.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error while saving data: " + e.getMessage());
        }
    }//GEN-LAST:event_register1ActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        LoginInterface login = new LoginInterface();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginActionPerformed

    private void cashierIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierIdActionPerformed

    }//GEN-LAST:event_cashierIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierRegisterInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierRegisterInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierRegisterInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierRegisterInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierRegisterInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JTextField cashierId;
    private javax.swing.JTextField cashierUsername;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField padtxt;
    private javax.swing.JLabel password;
    private javax.swing.JButton register1;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
